// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckTokenHandlerFunc turns a function with the right signature into a check token handler
type CheckTokenHandlerFunc func(CheckTokenParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckTokenHandlerFunc) Handle(params CheckTokenParams) middleware.Responder {
	return fn(params)
}

// CheckTokenHandler interface for that can handle valid check token params
type CheckTokenHandler interface {
	Handle(CheckTokenParams) middleware.Responder
}

// NewCheckToken creates a new http.Handler for the check token operation
func NewCheckToken(ctx *middleware.Context, handler CheckTokenHandler) *CheckToken {
	return &CheckToken{Context: ctx, Handler: handler}
}

/* CheckToken swagger:route POST /api/auth/check_token auth checkToken

CheckToken check token API

*/
type CheckToken struct {
	Context *middleware.Context
	Handler CheckTokenHandler
}

func (o *CheckToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckTokenParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
