// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// CheckTokenOKCode is the HTTP code returned for type CheckTokenOK
const CheckTokenOKCode int = 200

/*CheckTokenOK successful operation

swagger:response checkTokenOK
*/
type CheckTokenOK struct {
}

// NewCheckTokenOK creates CheckTokenOK with default headers values
func NewCheckTokenOK() *CheckTokenOK {

	return &CheckTokenOK{}
}

// WriteResponse to the client
func (o *CheckTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CheckTokenBadRequestCode is the HTTP code returned for type CheckTokenBadRequest
const CheckTokenBadRequestCode int = 400

/*CheckTokenBadRequest User not found

swagger:response checkTokenBadRequest
*/
type CheckTokenBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCheckTokenBadRequest creates CheckTokenBadRequest with default headers values
func NewCheckTokenBadRequest() *CheckTokenBadRequest {

	return &CheckTokenBadRequest{}
}

// WithPayload adds the payload to the check token bad request response
func (o *CheckTokenBadRequest) WithPayload(payload *models.Error) *CheckTokenBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check token bad request response
func (o *CheckTokenBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckTokenBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
