// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// IsAuthOKCode is the HTTP code returned for type IsAuthOK
const IsAuthOKCode int = 200

/*IsAuthOK successful operation

swagger:response isAuthOK
*/
type IsAuthOK struct {
}

// NewIsAuthOK creates IsAuthOK with default headers values
func NewIsAuthOK() *IsAuthOK {

	return &IsAuthOK{}
}

// WriteResponse to the client
func (o *IsAuthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// IsAuthBadRequestCode is the HTTP code returned for type IsAuthBadRequest
const IsAuthBadRequestCode int = 400

/*IsAuthBadRequest bad request

swagger:response isAuthBadRequest
*/
type IsAuthBadRequest struct {
}

// NewIsAuthBadRequest creates IsAuthBadRequest with default headers values
func NewIsAuthBadRequest() *IsAuthBadRequest {

	return &IsAuthBadRequest{}
}

// WriteResponse to the client
func (o *IsAuthBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// IsAuthUnauthorizedCode is the HTTP code returned for type IsAuthUnauthorized
const IsAuthUnauthorizedCode int = 401

/*IsAuthUnauthorized not valid token

swagger:response isAuthUnauthorized
*/
type IsAuthUnauthorized struct {
}

// NewIsAuthUnauthorized creates IsAuthUnauthorized with default headers values
func NewIsAuthUnauthorized() *IsAuthUnauthorized {

	return &IsAuthUnauthorized{}
}

// WriteResponse to the client
func (o *IsAuthUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
