// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// IsAuthHandlerFunc turns a function with the right signature into a is auth handler
type IsAuthHandlerFunc func(IsAuthParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn IsAuthHandlerFunc) Handle(params IsAuthParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// IsAuthHandler interface for that can handle valid is auth params
type IsAuthHandler interface {
	Handle(IsAuthParams, interface{}) middleware.Responder
}

// NewIsAuth creates a new http.Handler for the is auth operation
func NewIsAuth(ctx *middleware.Context, handler IsAuthHandler) *IsAuth {
	return &IsAuth{Context: ctx, Handler: handler}
}

/* IsAuth swagger:route GET /api/auth/is_auth auth isAuth

IsAuth is auth API

*/
type IsAuth struct {
	Context *middleware.Context
	Handler IsAuthHandler
}

func (o *IsAuth) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIsAuthParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
