// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// SendResetLinkOKCode is the HTTP code returned for type SendResetLinkOK
const SendResetLinkOKCode int = 200

/*SendResetLinkOK successful operation

swagger:response sendResetLinkOK
*/
type SendResetLinkOK struct {
}

// NewSendResetLinkOK creates SendResetLinkOK with default headers values
func NewSendResetLinkOK() *SendResetLinkOK {

	return &SendResetLinkOK{}
}

// WriteResponse to the client
func (o *SendResetLinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SendResetLinkBadRequestCode is the HTTP code returned for type SendResetLinkBadRequest
const SendResetLinkBadRequestCode int = 400

/*SendResetLinkBadRequest User not found

swagger:response sendResetLinkBadRequest
*/
type SendResetLinkBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSendResetLinkBadRequest creates SendResetLinkBadRequest with default headers values
func NewSendResetLinkBadRequest() *SendResetLinkBadRequest {

	return &SendResetLinkBadRequest{}
}

// WithPayload adds the payload to the send reset link bad request response
func (o *SendResetLinkBadRequest) WithPayload(payload *models.Error) *SendResetLinkBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the send reset link bad request response
func (o *SendResetLinkBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SendResetLinkBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SendResetLinkInternalServerErrorCode is the HTTP code returned for type SendResetLinkInternalServerError
const SendResetLinkInternalServerErrorCode int = 500

/*SendResetLinkInternalServerError Server error

swagger:response sendResetLinkInternalServerError
*/
type SendResetLinkInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSendResetLinkInternalServerError creates SendResetLinkInternalServerError with default headers values
func NewSendResetLinkInternalServerError() *SendResetLinkInternalServerError {

	return &SendResetLinkInternalServerError{}
}

// WithPayload adds the payload to the send reset link internal server error response
func (o *SendResetLinkInternalServerError) WithPayload(payload *models.Error) *SendResetLinkInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the send reset link internal server error response
func (o *SendResetLinkInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SendResetLinkInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
