// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger LawBox
//
//  Schemes:
//    http
//  Host: 127.0.0.1:8888
//  BasePath: /
//  Version: 1.0.0
//  Contact: <roman.dubatov@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
