// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// GetUserCreatedPostsOKCode is the HTTP code returned for type GetUserCreatedPostsOK
const GetUserCreatedPostsOKCode int = 200

/*GetUserCreatedPostsOK successful operation

swagger:response getUserCreatedPostsOK
*/
type GetUserCreatedPostsOK struct {

	/*
	  In: Body
	*/
	Payload *models.PostList `json:"body,omitempty"`
}

// NewGetUserCreatedPostsOK creates GetUserCreatedPostsOK with default headers values
func NewGetUserCreatedPostsOK() *GetUserCreatedPostsOK {

	return &GetUserCreatedPostsOK{}
}

// WithPayload adds the payload to the get user created posts o k response
func (o *GetUserCreatedPostsOK) WithPayload(payload *models.PostList) *GetUserCreatedPostsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user created posts o k response
func (o *GetUserCreatedPostsOK) SetPayload(payload *models.PostList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserCreatedPostsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserCreatedPostsBadRequestCode is the HTTP code returned for type GetUserCreatedPostsBadRequest
const GetUserCreatedPostsBadRequestCode int = 400

/*GetUserCreatedPostsBadRequest Bad request

swagger:response getUserCreatedPostsBadRequest
*/
type GetUserCreatedPostsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserCreatedPostsBadRequest creates GetUserCreatedPostsBadRequest with default headers values
func NewGetUserCreatedPostsBadRequest() *GetUserCreatedPostsBadRequest {

	return &GetUserCreatedPostsBadRequest{}
}

// WithPayload adds the payload to the get user created posts bad request response
func (o *GetUserCreatedPostsBadRequest) WithPayload(payload *models.Error) *GetUserCreatedPostsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user created posts bad request response
func (o *GetUserCreatedPostsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserCreatedPostsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserCreatedPostsUnauthorizedCode is the HTTP code returned for type GetUserCreatedPostsUnauthorized
const GetUserCreatedPostsUnauthorizedCode int = 401

/*GetUserCreatedPostsUnauthorized not valid token

swagger:response getUserCreatedPostsUnauthorized
*/
type GetUserCreatedPostsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserCreatedPostsUnauthorized creates GetUserCreatedPostsUnauthorized with default headers values
func NewGetUserCreatedPostsUnauthorized() *GetUserCreatedPostsUnauthorized {

	return &GetUserCreatedPostsUnauthorized{}
}

// WithPayload adds the payload to the get user created posts unauthorized response
func (o *GetUserCreatedPostsUnauthorized) WithPayload(payload *models.Error) *GetUserCreatedPostsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user created posts unauthorized response
func (o *GetUserCreatedPostsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserCreatedPostsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserCreatedPostsInternalServerErrorCode is the HTTP code returned for type GetUserCreatedPostsInternalServerError
const GetUserCreatedPostsInternalServerErrorCode int = 500

/*GetUserCreatedPostsInternalServerError Server error

swagger:response getUserCreatedPostsInternalServerError
*/
type GetUserCreatedPostsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserCreatedPostsInternalServerError creates GetUserCreatedPostsInternalServerError with default headers values
func NewGetUserCreatedPostsInternalServerError() *GetUserCreatedPostsInternalServerError {

	return &GetUserCreatedPostsInternalServerError{}
}

// WithPayload adds the payload to the get user created posts internal server error response
func (o *GetUserCreatedPostsInternalServerError) WithPayload(payload *models.Error) *GetUserCreatedPostsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user created posts internal server error response
func (o *GetUserCreatedPostsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserCreatedPostsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
