// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUserCreatedPostsHandlerFunc turns a function with the right signature into a get user created posts handler
type GetUserCreatedPostsHandlerFunc func(GetUserCreatedPostsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserCreatedPostsHandlerFunc) Handle(params GetUserCreatedPostsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUserCreatedPostsHandler interface for that can handle valid get user created posts params
type GetUserCreatedPostsHandler interface {
	Handle(GetUserCreatedPostsParams, interface{}) middleware.Responder
}

// NewGetUserCreatedPosts creates a new http.Handler for the get user created posts operation
func NewGetUserCreatedPosts(ctx *middleware.Context, handler GetUserCreatedPostsHandler) *GetUserCreatedPosts {
	return &GetUserCreatedPosts{Context: ctx, Handler: handler}
}

/* GetUserCreatedPosts swagger:route GET /api/user/posts/own user getUserCreatedPosts

Get posts created by user

*/
type GetUserCreatedPosts struct {
	Context *middleware.Context
	Handler GetUserCreatedPostsHandler
}

func (o *GetUserCreatedPosts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUserCreatedPostsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
