// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCartOKCode is the HTTP code returned for type GetCartOK
const GetCartOKCode int = 200

/*GetCartOK successful operation

swagger:response getCartOK
*/
type GetCartOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetCartOK creates GetCartOK with default headers values
func NewGetCartOK() *GetCartOK {

	return &GetCartOK{}
}

// WithPayload adds the payload to the get cart o k response
func (o *GetCartOK) WithPayload(payload string) *GetCartOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cart o k response
func (o *GetCartOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
