// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// GetUserPostsOKCode is the HTTP code returned for type GetUserPostsOK
const GetUserPostsOKCode int = 200

/*GetUserPostsOK successful operation

swagger:response getUserPostsOK
*/
type GetUserPostsOK struct {

	/*
	  In: Body
	*/
	Payload *models.PostList `json:"body,omitempty"`
}

// NewGetUserPostsOK creates GetUserPostsOK with default headers values
func NewGetUserPostsOK() *GetUserPostsOK {

	return &GetUserPostsOK{}
}

// WithPayload adds the payload to the get user posts o k response
func (o *GetUserPostsOK) WithPayload(payload *models.PostList) *GetUserPostsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user posts o k response
func (o *GetUserPostsOK) SetPayload(payload *models.PostList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserPostsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserPostsBadRequestCode is the HTTP code returned for type GetUserPostsBadRequest
const GetUserPostsBadRequestCode int = 400

/*GetUserPostsBadRequest Bad request

swagger:response getUserPostsBadRequest
*/
type GetUserPostsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserPostsBadRequest creates GetUserPostsBadRequest with default headers values
func NewGetUserPostsBadRequest() *GetUserPostsBadRequest {

	return &GetUserPostsBadRequest{}
}

// WithPayload adds the payload to the get user posts bad request response
func (o *GetUserPostsBadRequest) WithPayload(payload *models.Error) *GetUserPostsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user posts bad request response
func (o *GetUserPostsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserPostsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserPostsUnauthorizedCode is the HTTP code returned for type GetUserPostsUnauthorized
const GetUserPostsUnauthorizedCode int = 401

/*GetUserPostsUnauthorized not valid token

swagger:response getUserPostsUnauthorized
*/
type GetUserPostsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserPostsUnauthorized creates GetUserPostsUnauthorized with default headers values
func NewGetUserPostsUnauthorized() *GetUserPostsUnauthorized {

	return &GetUserPostsUnauthorized{}
}

// WithPayload adds the payload to the get user posts unauthorized response
func (o *GetUserPostsUnauthorized) WithPayload(payload *models.Error) *GetUserPostsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user posts unauthorized response
func (o *GetUserPostsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserPostsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserPostsInternalServerErrorCode is the HTTP code returned for type GetUserPostsInternalServerError
const GetUserPostsInternalServerErrorCode int = 500

/*GetUserPostsInternalServerError Server error

swagger:response getUserPostsInternalServerError
*/
type GetUserPostsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserPostsInternalServerError creates GetUserPostsInternalServerError with default headers values
func NewGetUserPostsInternalServerError() *GetUserPostsInternalServerError {

	return &GetUserPostsInternalServerError{}
}

// WithPayload adds the payload to the get user posts internal server error response
func (o *GetUserPostsInternalServerError) WithPayload(payload *models.Error) *GetUserPostsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user posts internal server error response
func (o *GetUserPostsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserPostsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
