// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// IsloginOKCode is the HTTP code returned for type IsloginOK
const IsloginOKCode int = 200

/*IsloginOK successful operation

swagger:response isloginOK
*/
type IsloginOK struct {
}

// NewIsloginOK creates IsloginOK with default headers values
func NewIsloginOK() *IsloginOK {

	return &IsloginOK{}
}

// WriteResponse to the client
func (o *IsloginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// IsloginUnauthorizedCode is the HTTP code returned for type IsloginUnauthorized
const IsloginUnauthorizedCode int = 401

/*IsloginUnauthorized not valid token

swagger:response isloginUnauthorized
*/
type IsloginUnauthorized struct {
}

// NewIsloginUnauthorized creates IsloginUnauthorized with default headers values
func NewIsloginUnauthorized() *IsloginUnauthorized {

	return &IsloginUnauthorized{}
}

// WriteResponse to the client
func (o *IsloginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
