// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// IsloginHandlerFunc turns a function with the right signature into a islogin handler
type IsloginHandlerFunc func(IsloginParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn IsloginHandlerFunc) Handle(params IsloginParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// IsloginHandler interface for that can handle valid islogin params
type IsloginHandler interface {
	Handle(IsloginParams, interface{}) middleware.Responder
}

// NewIslogin creates a new http.Handler for the islogin operation
func NewIslogin(ctx *middleware.Context, handler IsloginHandler) *Islogin {
	return &Islogin{Context: ctx, Handler: handler}
}

/* Islogin swagger:route GET /api/user/islogin user islogin

Islogin islogin API

*/
type Islogin struct {
	Context *middleware.Context
	Handler IsloginHandler
}

func (o *Islogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIsloginParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
