// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// UpdateUserInfoOKCode is the HTTP code returned for type UpdateUserInfoOK
const UpdateUserInfoOKCode int = 200

/*UpdateUserInfoOK successful operation

swagger:response updateUserInfoOK
*/
type UpdateUserInfoOK struct {
}

// NewUpdateUserInfoOK creates UpdateUserInfoOK with default headers values
func NewUpdateUserInfoOK() *UpdateUserInfoOK {

	return &UpdateUserInfoOK{}
}

// WriteResponse to the client
func (o *UpdateUserInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateUserInfoBadRequestCode is the HTTP code returned for type UpdateUserInfoBadRequest
const UpdateUserInfoBadRequestCode int = 400

/*UpdateUserInfoBadRequest Bad request

swagger:response updateUserInfoBadRequest
*/
type UpdateUserInfoBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateUserInfoBadRequest creates UpdateUserInfoBadRequest with default headers values
func NewUpdateUserInfoBadRequest() *UpdateUserInfoBadRequest {

	return &UpdateUserInfoBadRequest{}
}

// WithPayload adds the payload to the update user info bad request response
func (o *UpdateUserInfoBadRequest) WithPayload(payload *models.Error) *UpdateUserInfoBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user info bad request response
func (o *UpdateUserInfoBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserInfoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserInfoUnauthorizedCode is the HTTP code returned for type UpdateUserInfoUnauthorized
const UpdateUserInfoUnauthorizedCode int = 401

/*UpdateUserInfoUnauthorized not valid token

swagger:response updateUserInfoUnauthorized
*/
type UpdateUserInfoUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateUserInfoUnauthorized creates UpdateUserInfoUnauthorized with default headers values
func NewUpdateUserInfoUnauthorized() *UpdateUserInfoUnauthorized {

	return &UpdateUserInfoUnauthorized{}
}

// WithPayload adds the payload to the update user info unauthorized response
func (o *UpdateUserInfoUnauthorized) WithPayload(payload *models.Error) *UpdateUserInfoUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user info unauthorized response
func (o *UpdateUserInfoUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserInfoUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserInfoNotFoundCode is the HTTP code returned for type UpdateUserInfoNotFound
const UpdateUserInfoNotFoundCode int = 404

/*UpdateUserInfoNotFound User not found

swagger:response updateUserInfoNotFound
*/
type UpdateUserInfoNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateUserInfoNotFound creates UpdateUserInfoNotFound with default headers values
func NewUpdateUserInfoNotFound() *UpdateUserInfoNotFound {

	return &UpdateUserInfoNotFound{}
}

// WithPayload adds the payload to the update user info not found response
func (o *UpdateUserInfoNotFound) WithPayload(payload *models.Error) *UpdateUserInfoNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user info not found response
func (o *UpdateUserInfoNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserInfoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserInfoInternalServerErrorCode is the HTTP code returned for type UpdateUserInfoInternalServerError
const UpdateUserInfoInternalServerErrorCode int = 500

/*UpdateUserInfoInternalServerError Server error

swagger:response updateUserInfoInternalServerError
*/
type UpdateUserInfoInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateUserInfoInternalServerError creates UpdateUserInfoInternalServerError with default headers values
func NewUpdateUserInfoInternalServerError() *UpdateUserInfoInternalServerError {

	return &UpdateUserInfoInternalServerError{}
}

// WithPayload adds the payload to the update user info internal server error response
func (o *UpdateUserInfoInternalServerError) WithPayload(payload *models.Error) *UpdateUserInfoInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user info internal server error response
func (o *UpdateUserInfoInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
