// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UserPostsDeleteHandlerFunc turns a function with the right signature into a user posts delete handler
type UserPostsDeleteHandlerFunc func(UserPostsDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UserPostsDeleteHandlerFunc) Handle(params UserPostsDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UserPostsDeleteHandler interface for that can handle valid user posts delete params
type UserPostsDeleteHandler interface {
	Handle(UserPostsDeleteParams, interface{}) middleware.Responder
}

// NewUserPostsDelete creates a new http.Handler for the user posts delete operation
func NewUserPostsDelete(ctx *middleware.Context, handler UserPostsDeleteHandler) *UserPostsDelete {
	return &UserPostsDelete{Context: ctx, Handler: handler}
}

/* UserPostsDelete swagger:route POST /api/user/posts/delete user userPostsDelete

Delete post from favorite

*/
type UserPostsDelete struct {
	Context *middleware.Context
	Handler UserPostsDeleteHandler
}

func (o *UserPostsDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUserPostsDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
