// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UserPostsAddHandlerFunc turns a function with the right signature into a user posts add handler
type UserPostsAddHandlerFunc func(UserPostsAddParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UserPostsAddHandlerFunc) Handle(params UserPostsAddParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UserPostsAddHandler interface for that can handle valid user posts add params
type UserPostsAddHandler interface {
	Handle(UserPostsAddParams, interface{}) middleware.Responder
}

// NewUserPostsAdd creates a new http.Handler for the user posts add operation
func NewUserPostsAdd(ctx *middleware.Context, handler UserPostsAddHandler) *UserPostsAdd {
	return &UserPostsAdd{Context: ctx, Handler: handler}
}

/* UserPostsAdd swagger:route POST /api/user/posts/add user userPostsAdd

Add post in favorite

*/
type UserPostsAdd struct {
	Context *middleware.Context
	Handler UserPostsAddHandler
}

func (o *UserPostsAdd) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUserPostsAddParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
