// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddNewPostHandlerFunc turns a function with the right signature into a add new post handler
type AddNewPostHandlerFunc func(AddNewPostParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AddNewPostHandlerFunc) Handle(params AddNewPostParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AddNewPostHandler interface for that can handle valid add new post params
type AddNewPostHandler interface {
	Handle(AddNewPostParams, interface{}) middleware.Responder
}

// NewAddNewPost creates a new http.Handler for the add new post operation
func NewAddNewPost(ctx *middleware.Context, handler AddNewPostHandler) *AddNewPost {
	return &AddNewPost{Context: ctx, Handler: handler}
}

/* AddNewPost swagger:route POST /api/post/add post addNewPost

Add new posts

*/
type AddNewPost struct {
	Context *middleware.Context
	Handler AddNewPostHandler
}

func (o *AddNewPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddNewPostParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
