// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckPostInFavoriteHandlerFunc turns a function with the right signature into a check post in favorite handler
type CheckPostInFavoriteHandlerFunc func(CheckPostInFavoriteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckPostInFavoriteHandlerFunc) Handle(params CheckPostInFavoriteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CheckPostInFavoriteHandler interface for that can handle valid check post in favorite params
type CheckPostInFavoriteHandler interface {
	Handle(CheckPostInFavoriteParams, interface{}) middleware.Responder
}

// NewCheckPostInFavorite creates a new http.Handler for the check post in favorite operation
func NewCheckPostInFavorite(ctx *middleware.Context, handler CheckPostInFavoriteHandler) *CheckPostInFavorite {
	return &CheckPostInFavorite{Context: ctx, Handler: handler}
}

/* CheckPostInFavorite swagger:route GET /api/post/{id}/in_favorite post checkPostInFavorite

Check post in favorite

*/
type CheckPostInFavorite struct {
	Context *middleware.Context
	Handler CheckPostInFavoriteHandler
}

func (o *CheckPostInFavorite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckPostInFavoriteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
