// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeletePostMaterialHandlerFunc turns a function with the right signature into a delete post material handler
type DeletePostMaterialHandlerFunc func(DeletePostMaterialParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePostMaterialHandlerFunc) Handle(params DeletePostMaterialParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeletePostMaterialHandler interface for that can handle valid delete post material params
type DeletePostMaterialHandler interface {
	Handle(DeletePostMaterialParams, interface{}) middleware.Responder
}

// NewDeletePostMaterial creates a new http.Handler for the delete post material operation
func NewDeletePostMaterial(ctx *middleware.Context, handler DeletePostMaterialHandler) *DeletePostMaterial {
	return &DeletePostMaterial{Context: ctx, Handler: handler}
}

/* DeletePostMaterial swagger:route POST /api/post/{id}/materials/delete post deletePostMaterial

Delete posts material

*/
type DeletePostMaterial struct {
	Context *middleware.Context
	Handler DeletePostMaterialHandler
}

func (o *DeletePostMaterial) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeletePostMaterialParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
