// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// DeletePostMaterialOKCode is the HTTP code returned for type DeletePostMaterialOK
const DeletePostMaterialOKCode int = 200

/*DeletePostMaterialOK successful operation

swagger:response deletePostMaterialOK
*/
type DeletePostMaterialOK struct {
}

// NewDeletePostMaterialOK creates DeletePostMaterialOK with default headers values
func NewDeletePostMaterialOK() *DeletePostMaterialOK {

	return &DeletePostMaterialOK{}
}

// WriteResponse to the client
func (o *DeletePostMaterialOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeletePostMaterialBadRequestCode is the HTTP code returned for type DeletePostMaterialBadRequest
const DeletePostMaterialBadRequestCode int = 400

/*DeletePostMaterialBadRequest Bad request

swagger:response deletePostMaterialBadRequest
*/
type DeletePostMaterialBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePostMaterialBadRequest creates DeletePostMaterialBadRequest with default headers values
func NewDeletePostMaterialBadRequest() *DeletePostMaterialBadRequest {

	return &DeletePostMaterialBadRequest{}
}

// WithPayload adds the payload to the delete post material bad request response
func (o *DeletePostMaterialBadRequest) WithPayload(payload *models.Error) *DeletePostMaterialBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post material bad request response
func (o *DeletePostMaterialBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostMaterialBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostMaterialUnauthorizedCode is the HTTP code returned for type DeletePostMaterialUnauthorized
const DeletePostMaterialUnauthorizedCode int = 401

/*DeletePostMaterialUnauthorized not valid token

swagger:response deletePostMaterialUnauthorized
*/
type DeletePostMaterialUnauthorized struct {
}

// NewDeletePostMaterialUnauthorized creates DeletePostMaterialUnauthorized with default headers values
func NewDeletePostMaterialUnauthorized() *DeletePostMaterialUnauthorized {

	return &DeletePostMaterialUnauthorized{}
}

// WriteResponse to the client
func (o *DeletePostMaterialUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeletePostMaterialForbiddenCode is the HTTP code returned for type DeletePostMaterialForbidden
const DeletePostMaterialForbiddenCode int = 403

/*DeletePostMaterialForbidden Forbidden

swagger:response deletePostMaterialForbidden
*/
type DeletePostMaterialForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePostMaterialForbidden creates DeletePostMaterialForbidden with default headers values
func NewDeletePostMaterialForbidden() *DeletePostMaterialForbidden {

	return &DeletePostMaterialForbidden{}
}

// WithPayload adds the payload to the delete post material forbidden response
func (o *DeletePostMaterialForbidden) WithPayload(payload *models.Error) *DeletePostMaterialForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post material forbidden response
func (o *DeletePostMaterialForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostMaterialForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostMaterialInternalServerErrorCode is the HTTP code returned for type DeletePostMaterialInternalServerError
const DeletePostMaterialInternalServerErrorCode int = 500

/*DeletePostMaterialInternalServerError Server error

swagger:response deletePostMaterialInternalServerError
*/
type DeletePostMaterialInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePostMaterialInternalServerError creates DeletePostMaterialInternalServerError with default headers values
func NewDeletePostMaterialInternalServerError() *DeletePostMaterialInternalServerError {

	return &DeletePostMaterialInternalServerError{}
}

// WithPayload adds the payload to the delete post material internal server error response
func (o *DeletePostMaterialInternalServerError) WithPayload(payload *models.Error) *DeletePostMaterialInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post material internal server error response
func (o *DeletePostMaterialInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostMaterialInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
