// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// DeletePostOKCode is the HTTP code returned for type DeletePostOK
const DeletePostOKCode int = 200

/*DeletePostOK successful operation

swagger:response deletePostOK
*/
type DeletePostOK struct {
}

// NewDeletePostOK creates DeletePostOK with default headers values
func NewDeletePostOK() *DeletePostOK {

	return &DeletePostOK{}
}

// WriteResponse to the client
func (o *DeletePostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeletePostBadRequestCode is the HTTP code returned for type DeletePostBadRequest
const DeletePostBadRequestCode int = 400

/*DeletePostBadRequest Bad request

swagger:response deletePostBadRequest
*/
type DeletePostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePostBadRequest creates DeletePostBadRequest with default headers values
func NewDeletePostBadRequest() *DeletePostBadRequest {

	return &DeletePostBadRequest{}
}

// WithPayload adds the payload to the delete post bad request response
func (o *DeletePostBadRequest) WithPayload(payload *models.Error) *DeletePostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post bad request response
func (o *DeletePostBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostUnauthorizedCode is the HTTP code returned for type DeletePostUnauthorized
const DeletePostUnauthorizedCode int = 401

/*DeletePostUnauthorized not valid token

swagger:response deletePostUnauthorized
*/
type DeletePostUnauthorized struct {
}

// NewDeletePostUnauthorized creates DeletePostUnauthorized with default headers values
func NewDeletePostUnauthorized() *DeletePostUnauthorized {

	return &DeletePostUnauthorized{}
}

// WriteResponse to the client
func (o *DeletePostUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeletePostForbiddenCode is the HTTP code returned for type DeletePostForbidden
const DeletePostForbiddenCode int = 403

/*DeletePostForbidden Forbidden

swagger:response deletePostForbidden
*/
type DeletePostForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePostForbidden creates DeletePostForbidden with default headers values
func NewDeletePostForbidden() *DeletePostForbidden {

	return &DeletePostForbidden{}
}

// WithPayload adds the payload to the delete post forbidden response
func (o *DeletePostForbidden) WithPayload(payload *models.Error) *DeletePostForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post forbidden response
func (o *DeletePostForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostInternalServerErrorCode is the HTTP code returned for type DeletePostInternalServerError
const DeletePostInternalServerErrorCode int = 500

/*DeletePostInternalServerError Server error

swagger:response deletePostInternalServerError
*/
type DeletePostInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePostInternalServerError creates DeletePostInternalServerError with default headers values
func NewDeletePostInternalServerError() *DeletePostInternalServerError {

	return &DeletePostInternalServerError{}
}

// WithPayload adds the payload to the delete post internal server error response
func (o *DeletePostInternalServerError) WithPayload(payload *models.Error) *DeletePostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete post internal server error response
func (o *DeletePostInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
