// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRecommendedPostHandlerFunc turns a function with the right signature into a get recommended post handler
type GetRecommendedPostHandlerFunc func(GetRecommendedPostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRecommendedPostHandlerFunc) Handle(params GetRecommendedPostParams) middleware.Responder {
	return fn(params)
}

// GetRecommendedPostHandler interface for that can handle valid get recommended post params
type GetRecommendedPostHandler interface {
	Handle(GetRecommendedPostParams) middleware.Responder
}

// NewGetRecommendedPost creates a new http.Handler for the get recommended post operation
func NewGetRecommendedPost(ctx *middleware.Context, handler GetRecommendedPostHandler) *GetRecommendedPost {
	return &GetRecommendedPost{Context: ctx, Handler: handler}
}

/* GetRecommendedPost swagger:route POST /api/post/recommended post getRecommendedPost

Nearest post for main page

*/
type GetRecommendedPost struct {
	Context *middleware.Context
	Handler GetRecommendedPostHandler
}

func (o *GetRecommendedPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRecommendedPostParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
