// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPopularPostHandlerFunc turns a function with the right signature into a get popular post handler
type GetPopularPostHandlerFunc func(GetPopularPostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPopularPostHandlerFunc) Handle(params GetPopularPostParams) middleware.Responder {
	return fn(params)
}

// GetPopularPostHandler interface for that can handle valid get popular post params
type GetPopularPostHandler interface {
	Handle(GetPopularPostParams) middleware.Responder
}

// NewGetPopularPost creates a new http.Handler for the get popular post operation
func NewGetPopularPost(ctx *middleware.Context, handler GetPopularPostHandler) *GetPopularPost {
	return &GetPopularPost{Context: ctx, Handler: handler}
}

/* GetPopularPost swagger:route GET /api/post/popular post getPopularPost

Popular post for main page

*/
type GetPopularPost struct {
	Context *middleware.Context
	Handler GetPopularPostHandler
}

func (o *GetPopularPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPopularPostParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
