// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// GetPostByIDOKCode is the HTTP code returned for type GetPostByIDOK
const GetPostByIDOKCode int = 200

/*GetPostByIDOK successful operation

swagger:response getPostByIdOK
*/
type GetPostByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Post `json:"body,omitempty"`
}

// NewGetPostByIDOK creates GetPostByIDOK with default headers values
func NewGetPostByIDOK() *GetPostByIDOK {

	return &GetPostByIDOK{}
}

// WithPayload adds the payload to the get post by Id o k response
func (o *GetPostByIDOK) WithPayload(payload *models.Post) *GetPostByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get post by Id o k response
func (o *GetPostByIDOK) SetPayload(payload *models.Post) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPostByIDBadRequestCode is the HTTP code returned for type GetPostByIDBadRequest
const GetPostByIDBadRequestCode int = 400

/*GetPostByIDBadRequest Bad request

swagger:response getPostByIdBadRequest
*/
type GetPostByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPostByIDBadRequest creates GetPostByIDBadRequest with default headers values
func NewGetPostByIDBadRequest() *GetPostByIDBadRequest {

	return &GetPostByIDBadRequest{}
}

// WithPayload adds the payload to the get post by Id bad request response
func (o *GetPostByIDBadRequest) WithPayload(payload *models.Error) *GetPostByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get post by Id bad request response
func (o *GetPostByIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPostByIDInternalServerErrorCode is the HTTP code returned for type GetPostByIDInternalServerError
const GetPostByIDInternalServerErrorCode int = 500

/*GetPostByIDInternalServerError Server error

swagger:response getPostByIdInternalServerError
*/
type GetPostByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPostByIDInternalServerError creates GetPostByIDInternalServerError with default headers values
func NewGetPostByIDInternalServerError() *GetPostByIDInternalServerError {

	return &GetPostByIDInternalServerError{}
}

// WithPayload adds the payload to the get post by Id internal server error response
func (o *GetPostByIDInternalServerError) WithPayload(payload *models.Error) *GetPostByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get post by Id internal server error response
func (o *GetPostByIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
