// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateLinkInPostHandlerFunc turns a function with the right signature into a update link in post handler
type UpdateLinkInPostHandlerFunc func(UpdateLinkInPostParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateLinkInPostHandlerFunc) Handle(params UpdateLinkInPostParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateLinkInPostHandler interface for that can handle valid update link in post params
type UpdateLinkInPostHandler interface {
	Handle(UpdateLinkInPostParams, interface{}) middleware.Responder
}

// NewUpdateLinkInPost creates a new http.Handler for the update link in post operation
func NewUpdateLinkInPost(ctx *middleware.Context, handler UpdateLinkInPostHandler) *UpdateLinkInPost {
	return &UpdateLinkInPost{Context: ctx, Handler: handler}
}

/* UpdateLinkInPost swagger:route POST /api/post/{id}/update_link post updateLinkInPost

Update link in post.

*/
type UpdateLinkInPost struct {
	Context *middleware.Context
	Handler UpdateLinkInPostHandler
}

func (o *UpdateLinkInPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateLinkInPostParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
