// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lawSite/models"
)

// UpdatePostOKCode is the HTTP code returned for type UpdatePostOK
const UpdatePostOKCode int = 200

/*UpdatePostOK successful operation

swagger:response updatePostOK
*/
type UpdatePostOK struct {
}

// NewUpdatePostOK creates UpdatePostOK with default headers values
func NewUpdatePostOK() *UpdatePostOK {

	return &UpdatePostOK{}
}

// WriteResponse to the client
func (o *UpdatePostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdatePostBadRequestCode is the HTTP code returned for type UpdatePostBadRequest
const UpdatePostBadRequestCode int = 400

/*UpdatePostBadRequest Bad request

swagger:response updatePostBadRequest
*/
type UpdatePostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdatePostBadRequest creates UpdatePostBadRequest with default headers values
func NewUpdatePostBadRequest() *UpdatePostBadRequest {

	return &UpdatePostBadRequest{}
}

// WithPayload adds the payload to the update post bad request response
func (o *UpdatePostBadRequest) WithPayload(payload *models.Error) *UpdatePostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update post bad request response
func (o *UpdatePostBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdatePostUnauthorizedCode is the HTTP code returned for type UpdatePostUnauthorized
const UpdatePostUnauthorizedCode int = 401

/*UpdatePostUnauthorized not valid token

swagger:response updatePostUnauthorized
*/
type UpdatePostUnauthorized struct {
}

// NewUpdatePostUnauthorized creates UpdatePostUnauthorized with default headers values
func NewUpdatePostUnauthorized() *UpdatePostUnauthorized {

	return &UpdatePostUnauthorized{}
}

// WriteResponse to the client
func (o *UpdatePostUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// UpdatePostForbiddenCode is the HTTP code returned for type UpdatePostForbidden
const UpdatePostForbiddenCode int = 403

/*UpdatePostForbidden Forbidden

swagger:response updatePostForbidden
*/
type UpdatePostForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdatePostForbidden creates UpdatePostForbidden with default headers values
func NewUpdatePostForbidden() *UpdatePostForbidden {

	return &UpdatePostForbidden{}
}

// WithPayload adds the payload to the update post forbidden response
func (o *UpdatePostForbidden) WithPayload(payload *models.Error) *UpdatePostForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update post forbidden response
func (o *UpdatePostForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePostForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdatePostInternalServerErrorCode is the HTTP code returned for type UpdatePostInternalServerError
const UpdatePostInternalServerErrorCode int = 500

/*UpdatePostInternalServerError Server error

swagger:response updatePostInternalServerError
*/
type UpdatePostInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdatePostInternalServerError creates UpdatePostInternalServerError with default headers values
func NewUpdatePostInternalServerError() *UpdatePostInternalServerError {

	return &UpdatePostInternalServerError{}
}

// WithPayload adds the payload to the update post internal server error response
func (o *UpdatePostInternalServerError) WithPayload(payload *models.Error) *UpdatePostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update post internal server error response
func (o *UpdatePostInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
