// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResetToken reset token
//
// swagger:model ResetToken
type ResetToken struct {

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this reset token
func (m *ResetToken) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this reset token based on context it is used
func (m *ResetToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResetToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResetToken) UnmarshalBinary(b []byte) error {
	var res ResetToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
