// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Sort sort
//
// swagger:model Sort
type Sort struct {

	// key
	Key string `json:"key,omitempty"`

	// Sort order:
	//  * `asc` - Ascending, from A to Z
	//  * `desc` - Descending, from Z to A
	//
	// Enum: [asc desc]
	Order string `json:"order,omitempty"`
}

// Validate validates this sort
func (m *Sort) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrder(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var sortTypeOrderPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["asc","desc"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sortTypeOrderPropEnum = append(sortTypeOrderPropEnum, v)
	}
}

const (

	// SortOrderAsc captures enum value "asc"
	SortOrderAsc string = "asc"

	// SortOrderDesc captures enum value "desc"
	SortOrderDesc string = "desc"
)

// prop value enum
func (m *Sort) validateOrderEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, sortTypeOrderPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Sort) validateOrder(formats strfmt.Registry) error {
	if swag.IsZero(m.Order) { // not required
		return nil
	}

	// value enum
	if err := m.validateOrderEnum("order", "body", m.Order); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sort based on context it is used
func (m *Sort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Sort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Sort) UnmarshalBinary(b []byte) error {
	var res Sort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
